name: Alerts Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # Executa toda segunda-feira à meia-noite

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install
        continue-on-error: false

      - name: Run security audit
        run: npm audit || true
        continue-on-error: true

      - name: Mock email notification
        if: failure()
        run: |
          echo "=== SIMULAÇÃO DE NOTIFICAÇÃO DE SEGURANÇA ==="
          echo "Para: juliapadilhadarosa@hotmail.com"
          echo "Assunto: ⚠️ Alerta de Segurança - Projeto login-app"
          echo "Corpo: Foi detectado um problema de segurança no projeto login-app."
          echo "=== FIM DA SIMULAÇÃO ==="

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install
        continue-on-error: false

      - name: Check outdated dependencies
        run: npm outdated || true
        continue-on-error: true
        
      - name: Mock dependency report email
        run: |
          echo "=== SIMULAÇÃO DE RELATÓRIO DE DEPENDÊNCIAS ==="
          echo "Para: juliapadilhadarosa@hotmail.com"
          echo "Assunto: 📦 Relatório de Dependências - Projeto login-app"
          echo "Corpo: Aqui está o relatório de dependências do seu projeto login-app."
          echo "=== FIM DA SIMULAÇÃO ==="